kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: jenkins-slave-soapui
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'jenkins-slave-soapui:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy: {}
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/sholly/jenkins-slave-soapui'
      ref: main
  runPolicy: Serial
